[Settings]

[build]
  base = "apps/functions"

[functions]
  directory = "src"
  included_files = ["src/GetAllVehiclesForRoutes/data/*.json"]

[[redirects]]
  from = "/api/InfoPoint/rest/Vehicles/GetAllVehiclesForRoutes"
  to = "/.netlify/functions/GetAllVehiclesForRoutes/:splat"
  status = 200
  force = true