[Settings]

[build]
  base = "apps/functions"
  command = "yarn install"

[functions]
  directory = "src"

[[redirects]]
  from = "/api/InfoPoint/rest/Vehicles/GetAllVehiclesForRoutes"
  to = "/.netlify/functions/GetAllVehiclesForRoutes/:splat"
  status = 200
  force = true